services:
  inventory-db:
    build:
      context: srcs/postgres-db
    restart: always
    volumes:
      - inventory-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${INVENTORY_DB_USER}
      - POSTGRES_DB=${INVENTORY_DB_NAME}
      - POSTGRES_PASSWORD=${INVENTORY_DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 3s
      timeout: 1s
      retries: 5

  inventory-app:
    restart: always
    build:
      context: srcs/inventory-app
    env_file: .env
    expose:
      - ${INVENTORY_APP_PORT}
    depends_on:
      inventory-db:
        condition: service_healthy

  billing-db:
    build:
      context: srcs/postgres-db
    restart: always
    volumes:
      - billing-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${BILLING_DB_USER}
      - POSTGRES_DB=${BILLING_DB_NAME}
      - POSTGRES_PASSWORD=${BILLING_DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 3s
      timeout: 1s
      retries: 5

  billing-queue:
    build:
      context: srcs/rabbitmq
    hostname: billing-queue
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - billing-queue:/var/lib/rabbitmq
    expose:
      - ${RABBITMQ_PORT}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  billing-app:
    build:
      context: srcs/billing-app
    env_file: .env
    restart: always
    environment:
      - RABBITMQ_HOST=billing-queue
    expose:
      - ${BILLING_APP_PORT}
    depends_on:
      billing-db:
        condition: service_healthy
      billing-queue:
        condition: service_healthy

  api-gateway:
    build:
      context: srcs/api-gateway-app
    restart: always
    env_file: .env
    environment:
      - RABBITMQ_HOST=billing-queue
      - INVENTORY_APP_HOST=inventory-app
      - BILLING_APP_HOST=billing-app
    ports:
      - "3001:3000"
    depends_on:
      billing-queue:
        condition: service_healthy

volumes:
  inventory-database:
  billing-database:
  billing-queue:
