apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
spec:
  replicas: 1
  serviceName : billing-db
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      containers:
        - name: billing-db
          image: mohaa04/billing-db:latest        
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: billing-db-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi                             