apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  replicas: 1
  serviceName: inventory-db  
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db   
    spec:
      containers:
        - name: inventory-db
          image: mohaa04/inventory-db:latest
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: inventory-db-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data #même nom que volumeMounts
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi        
