apiVersion: v1
kind: Secret
metadata:
  name: rabbit-queue-secret
stringData:
  RABBITMQ_DEFAULT_USER: "rabbit"
  RABBITMQ_DEFAULT_PASS: "password"
  RABBITMQ_USER: "rabbit"
  RABBITMQ_PASSWORD: "password"
  RABBITMQ_QUEUE: "billing_queue"